export const orders = [
  {
    id: 1,
    orderNo: "0001",
    customer: "Deveci Otomotiv",
    channel: "Instagram",
    contact: "@deveciotomotiv",
    processDate: "2026-06-19",
    workDays: 12,
    totalPrice: 3500,
    paidAmount: 1750,
    cariAmount: 2100,
    profit: 1400,
    cariPaid: false,
    status: "İşleme Alındı",
    items: [
      {
        productType: "Oto Kokusu",
        material: "Tek Kat",
        quantity: 500,
        essenceCategory: "Standart",
        essence: "Vanilya",
      },
      {
        productType: "Oto Kokusu",
        material: "Tek Kat",
        quantity: 500,
        essenceCategory: "Standart",
        essence: "Okyanus",
      },
    ],
  },
  {
    id: 2,
    orderNo: "0002",
    customer: "Tamer Motor",
    channel: "WhatsApp",
    contact: "0532 000 00 00",
    processDate: "2026-06-23",
    workDays: 19,
    totalPrice: 7200,
    paidAmount: 7200,
    cariAmount: 4400,
    profit: 2800,
    cariPaid: true,
    status: "İşleme Alındı",
    items: [
      {
        productType: "Sırt Kartonlu",
        material: "Selüloz",
        quantity: 1000,
        essenceCategory: "VIP",
        essence: "Sauvage / Dior",
      },
    ],
  },
  {
    id: 3,
    orderNo: "0003",
    customer: "Ünanlar Otomotiv",
    channel: "Instagram",
    contact: "@unanlaroto",
    processDate: "2026-07-01",
    workDays: 7,
    totalPrice: 4500,
    paidAmount: 3000,
    cariAmount: 2500,
    profit: 2000,
    cariPaid: false,
    status: "Kargo Çıktı",
    items: [
      {
        productType: "Paspas",
        material: "Yok",
        quantity: 100,
        essenceCategory: "Yok",
        essence: "Yok",
      },
    ],
  },
];