export const essences = [
  {
    category: "Standart Esanslar",
    items: [
      "Okyanus",
      "Sakız",
      "Portakal",
      "Çilek",
      "Limon",
      "Bahar",
      "Fresh",
      "Mentol",
      "Hanımeli",
      "Mango",
      "Elma",
      "Lavanta",
      "Vanilya",
      "Blackberry / Böğürtlen",
      "Latte / Sütlü Kahve",
      "Çam",
      "Kavun",
      "Tropik Meyve",
      "Burcu / Dove",
      "Kiraz Çiçeği / Sakura",
    ],
  },
  {
    category: "Parfüm Esanslar",
    items: [
      "Bambu",
      "Rain Forest",
      "Jeune France",
      "Hollywood",
      "One Million",
      "Areon Vanilya",
      "Woody",
      "Little Trees New Car",
      "Little Trees Amerikan Vanilya",
      "Little Trees Black Ice",
    ],
  },
  {
    category: "VIP Esanslar",
    items: [
      "Tom Ford Black Orchid",
      "Inviktus",
      "Boss",
      "Jampol",
      "Angel",
      "Zafira",
      "Issey Miyaki",
      "Burberry Weekend",
      "Sauvage / Dior",
      "Blue De Channell",
    ],
  },
  {
    category: "Özel / Diğer",
    items: ["Özel Esans Yazılacak"],
  },
];